[en]
  title = "Thomas Treffner Tech"
  languageName = "English"
  weight = 1
  languagedir = "ltr"
  contentdir = "content/en"

[de]
  title = "Thomas Treffner Tech"
  languageName = "Deutsch"
  weight = 2
  languagedir = "ltr"
  contentdir = "content/de"
